name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t dvr-scan-file-organizer .

      - name: Code Quality Checks
        run: |
          docker run --rm -v ${{ github.workspace }}/dvr_scan_file_organizer:/app/dvr_scan_file_organizer \
            --entrypoint black dvr-scan-file-organizer --check /app/dvr_scan_file_organizer
          
          docker run --rm -e PYTHONPATH=/app \
            -v ${{ github.workspace }}/dvr_scan_file_organizer:/app/dvr_scan_file_organizer \
            --entrypoint pylint dvr-scan-file-organizer dvr_scan_file_organizer

      - name: Run Tests
        run: |
          docker run --rm -e PYTHONPATH=/app \
            -v ${{ github.workspace }}/dvr_scan_file_organizer:/app/dvr_scan_file_organizer \
            -v ${{ github.workspace }}/tests:/app/tests \
            --entrypoint pytest dvr-scan-file-organizer tests
