name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t dvrscan-organizer .

      - name: Run Linting
        run: |
          docker run --rm -e PYTHONPATH=/app \
          -v ${{ github.workspace }}/dvrscan_organizer:/app/dvrscan_organizer \
          -v ${{ github.workspace }}/tests:/app/tests \
          --entrypoint pylint dvrscan-organizer dvrscan_organizer tests

      - name: Run Tests
        run: |
          docker run --rm -e PYTHONPATH=/app \
          -v ${{ github.workspace }}/dvrscan_organizer:/app/dvrscan_organizer \
          -v ${{ github.workspace }}/tests:/app/tests \
          --entrypoint pytest dvrscan-organizer tests
